# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GL20.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GL20.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nGL20.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"\x0b\n\tnoMessage2g\n\x0bserviceGL20\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x12\x36\n\x1aGL20_digitalWriteToggleAll\x12\n.noMessage\x1a\n.noMessage\"\x00\x62\x06proto3'
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=37,
)


_NOMESSAGE = _descriptor.Descriptor(
  name='noMessage',
  full_name='noMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['noMessage'] = _NOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'GL20_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

noMessage = _reflection.GeneratedProtocolMessageType('noMessage', (_message.Message,), {
  'DESCRIPTOR' : _NOMESSAGE,
  '__module__' : 'GL20_pb2'
  # @@protoc_insertion_point(class_scope:noMessage)
  })
_sym_db.RegisterMessage(noMessage)



_SERVICEGL20 = _descriptor.ServiceDescriptor(
  name='serviceGL20',
  full_name='serviceGL20',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=52,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='serviceGL20.SquareRoot',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GL20_digitalWriteToggleAll',
    full_name='serviceGL20.GL20_digitalWriteToggleAll',
    index=1,
    containing_service=None,
    input_type=_NOMESSAGE,
    output_type=_NOMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICEGL20)

DESCRIPTOR.services_by_name['serviceGL20'] = _SERVICEGL20

# @@protoc_insertion_point(module_scope)
