# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GL20_pb2 as GL20__pb2


class serviceGL20Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SquareRoot = channel.unary_unary(
                '/serviceGL20/SquareRoot',
                request_serializer=GL20__pb2.Number.SerializeToString,
                response_deserializer=GL20__pb2.Number.FromString,
                )
        self.GL20_digitalWriteToggleAll = channel.unary_unary(
                '/serviceGL20/GL20_digitalWriteToggleAll',
                request_serializer=GL20__pb2.noMessage.SerializeToString,
                response_deserializer=GL20__pb2.noMessage.FromString,
                )


class serviceGL20Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def SquareRoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GL20_digitalWriteToggleAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceGL20Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SquareRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.SquareRoot,
                    request_deserializer=GL20__pb2.Number.FromString,
                    response_serializer=GL20__pb2.Number.SerializeToString,
            ),
            'GL20_digitalWriteToggleAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GL20_digitalWriteToggleAll,
                    request_deserializer=GL20__pb2.noMessage.FromString,
                    response_serializer=GL20__pb2.noMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serviceGL20', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class serviceGL20(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SquareRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serviceGL20/SquareRoot',
            GL20__pb2.Number.SerializeToString,
            GL20__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GL20_digitalWriteToggleAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serviceGL20/GL20_digitalWriteToggleAll',
            GL20__pb2.noMessage.SerializeToString,
            GL20__pb2.noMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
